### PR TITLE
feature#48-Structure and style of seller phones screen

### PR DESCRIPTION
**Pull request by M-Cordova-M**
# Description

I created the base for the seller display just the style and structure, based on the figma prototype design, thi way we can add functionality using the API in future issues.

## Screenshots
image

### CODE REVIEW

**Review by xManuel007 — APPROVED** [review]

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by YilKanda — CHANGES_REQUESTED** [review]
Check the conflicts

image

**Comment by M-Cordova-M** [comment]
> Check the conflicts
> 
> image

Conflicts have been resolved.

**Review by YilKanda — APPROVED** [review]
LGTM!

**Pull request merged**
